### PR TITLE
Remove is_superuser from resource API

### PR DESCRIPTION
**Pull request by fosterseth**
Do not sync is_superuser field on Users.

### CODE REVIEW

**Review by AlanCoding — APPROVED** [review]
so it is written, so it shall be done

**Comment by AlanCoding** [comment]
Documenting for hazard assessment:

https://github.com/ansible/awx/blob/444af2b500517e0cc09f791b7775d4b5b5ed6cf4/awx/api/views/__init__.py#L753-L769

AWX code enforces `ALLOW_LOCAL_RESOURCE_MANAGEMENT`, and it will allow updates of non-shared fields even if "local management" is _not_ allowed. With this, `is_superuser` becomes a non-shared field, so it should work as intended.

**Comment by AlanCoding** [comment]
But... I'm worried about eda-server and galaxy_ng

https://github.com/ansible/eda-server/blob/48b44cf06d4d0498d490810a043b4b3cf44578ac/src/aap_eda/api/serializers/mixins.py#L22-L27

and galaxy_ng

https://github.com/ansible/galaxy_ng/blob/b1c841132c4d3d27c3d0ae5ce5b744a656ef4bab/galaxy_ng/app/access_control/statements/standalone.py#L164-L167

**Review by shanemcd — DISMISSED** [review]
Talking with Alan now, please hold up.

**Review by AlanCoding — CHANGES_REQUESTED** [review]
yep, hold for investigation of last comments

**Review by AlanCoding — APPROVED** [review]
We have supporting patches to enable this. After some discussion, I'm not particular about merge order. Ping @elyezer

**Comment by AlanCoding** [comment]
Dependent PRs have merged, https://github.com/ansible/galaxy_ng/pull/2255 and https://github.com/ansible/eda-server/pull/1043

**Pull request merged**
