### PR TITLE
[HOLD] Remove ANSIBLE_BASE_ROLE_PRECREATE only used by AWX

### PR DESCRIPTION
**Pull request by AlanCoding**
Opening as a draft initially, the work is going on separately in AWX, along with the role rename.

The AWX change is a blocker for merging this, but I want to be sure everything is passing here.

eda-server did not use this, and I do not anticipate galaxy_ng will either, but I await confirmation of that. If you plan to use this, we can keep it.

### CODE REVIEW

**Comment by AlanCoding** [comment]
Since https://github.com/ansible/awx/pull/15087 is merged, this can be taken out of draft... right after a rebase.

**Review by relrod — APPROVED** [review]

**Comment by john-westcott-iv** [comment]
@newswangerd can you take a look at this and give it a thumbs up if we're good to merge?

**Review by newswangerd — APPROVED** [review]
Is there another mechanism for pre creating roles in place?

**Comment by AlanCoding** [comment]
We might hold off on merging (at least for a bit), as we're still not totally sure if other apps might use this.

**Comment by john-westcott-iv** [comment]
Checked with @AlanCoding this is still on hold.

**Comment by AlanCoding** [comment]
Note: I wanted to see that the "Testing DAB Consumers" check (introduced after this was created) was passing after a rebase, and it is, so it looks like we're good there.

https://github.com/ansible/django-ansible-base/pull/435 includes the commit from this, and now also proposes a new replacement system. My focus is going to be on that, so I'm going to close this PR for now, with the note that these changes are included completely there.

**Pull request closed without merging**
