### PR TITLE
RBAC: User can't delete self

### PR DESCRIPTION
**Pull request by slemrmartin**
User shouldn't have an ability to delete self.

### CODE REVIEW

**Comment by AlanCoding** [comment]
Is this really a _permission_ check though? Doesn't this apply to superusers? Should a superuser get a _403_ when trying to delete themselves? Should they get a message that reads "You don't have permission to perform this action" in the response?

A shared `CommonUserSerializer` was just introduced. And I know, I know, you can't enforce deletion rules using the serializer. That's not going to help you, but it seems like a better place.

This is just too low in the stack for me to put this check. If you must raise a `PermissionDenied` (as opposed to another exception), then put a custom message with it.

**Comment by slemrmartin** [comment]
In my opinion this is a permission check, it's a Delete permission. 
Serializer validates changes in fields, not this kind of "change".
It should be valid also for superusers as we discussed it in the RBAC doc. 

What could be the alternative (but I don't think it's worth the effort)  - that superuser can delete self, except if it's the last superuser in the system - that check should be part of serializer's validation.
But this simple check covers that condition too with much less and simpler code

**Comment by AlanCoding** [comment]
Then could you raise a PermissionDenied exception with a message explaining "you can't delete yourself" (would have to move to the permission class)? This is going down the path of non-trivial undocumented policies rules, which can be extremely bad for the user experience.

**Comment by slemrmartin** [comment]
changed as suggested

**Review by AlanCoding — APPROVED** [review]
thanks!

**Pull request merged**
